export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// auth

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER';

export const PASSWORD_RESET_ERROR = 'PASSWORD_RESET_ERROR';
export const FORGOT_PASSWORD_ERRORS = 'FORGOT_PASSWORD_ERRORS';
export const PASSWORD_RESET = 'PASSWORD_RESET';
export const SETTINGS_SUCCESS = 'SETTINGS_SUCCESS';
export const SETTINGS__FAIL = 'SETTINGS__FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const EMAIL_VERIFIED = 'EMAIL_VERIFIED';
export const EMAIL_VERIFIED_FAILED = 'EMAIL_VERIFIED_FAILED';
